// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type Url struct {
	ID        int32
	ShortUrl  string
	LongUrl   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int32
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
