// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type Url struct {
	ID        int32
	ShortUrl  string
	LongUrl   string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    int32
}

type User struct {
	ID                     int32
	Email                  string
	Password               string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	RefreshToken           sql.NullString
	RefreshTokenRevokeDate sql.NullTime
}
