// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: urls.sql

package database

import (
	"context"
	"time"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (short_url, long_url, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, short_url, long_url, created_at, updated_at
`

type CreateURLParams struct {
	ShortUrl  string
	LongUrl   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL,
		arg.ShortUrl,
		arg.LongUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.LongUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectURL = `-- name: SelectURL :one
SELECT id, short_url, long_url, created_at, updated_at 
FROM urls
WHERE short_url = $1
`

func (q *Queries) SelectURL(ctx context.Context, shortUrl string) (Url, error) {
	row := q.db.QueryRowContext(ctx, selectURL, shortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.LongUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
